#!/usr/bin/env python3
"""Generate the canonical Phase 3C installation-profile v1 binary golden."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from animation.core.installation_profile import (  # noqa: E402
    GLOBAL_STRIP_COUNT,
    LEDS_PER_STRIP,
    compile_installation_profile,
    encode_installation_profile,
)
from animation.core.installation_profile_topology import (  # noqa: E402
    INSTALLED_INSTALLATION_PROFILE_TOPOLOGY,
    RECEIVER_COUNT,
    RECEIVER_STRIP_COUNTS,
    slice_installation_profile,
)


DEFAULT_OUTPUT = REPO_ROOT / "tests" / "fixtures" / "installation_profile_v1.bin"
DEFAULT_RECEIVER_HEADER = (
    REPO_ROOT
    / "firmware"
    / "esp32"
    / "test"
    / "fixtures"
    / "installation_profile_receiver_v1.hpp"
)
FOLIAGE_INPUT = REPO_ROOT / "config" / "plant_pixel_map_32x138.json"
GLOBES_INPUT = REPO_ROOT / "config" / "plant_globe_map_32x138.json"
REGIONS_INPUT = REPO_ROOT / "config" / "plant_globe_regions_32x138.json"
WALL_INPUT = REPO_ROOT / "config" / "webcam_wall_calibration.json"
CLEARANCE_RADIUS = 1


def build_fixture() -> bytes:
    """Compile the checked-in calibration inputs into deterministic v1 bytes."""

    profile = compile_installation_profile(
        foliage_path=FOLIAGE_INPUT,
        globes_path=GLOBES_INPUT,
        regions_path=REGIONS_INPUT,
        wall_path=WALL_INPUT,
        clearance_radius=CLEARANCE_RADIUS,
    )
    return encode_installation_profile(profile)


def build_receiver_fixtures() -> tuple[bytes, ...]:
    """Return installed-topology receiver views in logical-ID order."""

    profile = compile_installation_profile(
        foliage_path=FOLIAGE_INPUT,
        globes_path=GLOBES_INPUT,
        regions_path=REGIONS_INPUT,
        wall_path=WALL_INPUT,
        clearance_radius=CLEARANCE_RADIUS,
    )
    views = slice_installation_profile(
        profile, INSTALLED_INSTALLATION_PROFILE_TOPOLOGY
    )
    return tuple(
        encode_installation_profile(views[index])
        for index in range(RECEIVER_COUNT)
    )


def build_receiver_header() -> bytes:
    """Render deterministic C++ fixtures for the portable firmware decoder."""

    fixtures = build_receiver_fixtures()
    origins = tuple(
        INSTALLED_INSTALLATION_PROFILE_TOPOLOGY
        .strip_origin_for_logical_receiver(index)
        for index in range(RECEIVER_COUNT)
    )
    reversed_order = (
        INSTALLED_INSTALLATION_PROFILE_TOPOLOGY
        .reverse_native_strips_by_logical_receiver
    )
    lines = [
        "// Generated by tools/fixtures/generate_installation_profile_golden.py.",
        "// Do not edit by hand.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace ledgrid::installation_profile_fixture {",
        "",
    ]
    for logical_id, payload in enumerate(fixtures):
        lines.append(
            f"inline constexpr std::uint8_t kReceiver{logical_id}[] = {{"
        )
        for offset in range(0, len(payload), 16):
            chunk = payload[offset : offset + 16]
            lines.append(
                "    " + ", ".join(f"0x{value:02x}" for value in chunk) + ","
            )
        lines.extend(("};", ""))
    lines.extend(
        (
            "struct Fixture {",
            "  const std::uint8_t* bytes;",
            "  std::size_t size;",
            "  std::uint16_t global_strip_count;",
            "  std::uint16_t strip_origin;",
            "  std::uint16_t strip_count;",
            "  std::uint16_t leds_per_strip;",
            "  bool reversed_strip_order;",
            "};",
            "",
            "inline constexpr Fixture kInstalledReceivers[] = {",
        )
    )
    for logical_id, (origin, reversed_value) in enumerate(
        zip(origins, reversed_order)
    ):
        flag = "true" if reversed_value else "false"
        lines.append(
            f"    {{kReceiver{logical_id}, sizeof(kReceiver{logical_id}), "
            f"{GLOBAL_STRIP_COUNT}, {origin}, {RECEIVER_STRIP_COUNTS[logical_id]}, "
            f"{LEDS_PER_STRIP}, {flag}}},"
        )
    lines.extend(
        ("};", "", "}  // namespace ledgrid::installation_profile_fixture", "")
    )
    return "\n".join(lines).encode("ascii")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--receiver-header",
        type=Path,
        help="also generate the installed receiver views as a C++ header",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the generated bytes differ",
    )
    args = parser.parse_args(argv)
    generated = build_fixture()

    if args.check:
        if not args.output.is_file() or args.output.read_bytes() != generated:
            parser.error(f"fixture is stale; regenerate {args.output}")
        if args.receiver_header is not None:
            receiver_header = build_receiver_header()
            if (
                not args.receiver_header.is_file()
                or args.receiver_header.read_bytes() != receiver_header
            ):
                parser.error(
                    f"fixture is stale; regenerate {args.receiver_header}"
                )
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated)
    if args.receiver_header is not None:
        args.receiver_header.parent.mkdir(parents=True, exist_ok=True)
        args.receiver_header.write_bytes(build_receiver_header())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
