#!/usr/bin/env python3
"""Generate the canonical Phase 3C installation-profile v1 binary golden."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from animation.core.installation_profile import (  # noqa: E402
    compile_installation_profile,
    encode_installation_profile,
)


DEFAULT_OUTPUT = REPO_ROOT / "tests" / "fixtures" / "installation_profile_v1.bin"
FOLIAGE_INPUT = REPO_ROOT / "config" / "plant_pixel_map_32x138.json"
GLOBES_INPUT = REPO_ROOT / "config" / "plant_globe_map_32x138.json"
REGIONS_INPUT = REPO_ROOT / "config" / "plant_globe_regions_32x138.json"
WALL_INPUT = REPO_ROOT / "config" / "webcam_wall_calibration.json"
CLEARANCE_RADIUS = 1


def build_fixture() -> bytes:
    """Compile the checked-in calibration inputs into deterministic v1 bytes."""

    profile = compile_installation_profile(
        foliage_path=FOLIAGE_INPUT,
        globes_path=GLOBES_INPUT,
        regions_path=REGIONS_INPUT,
        wall_path=WALL_INPUT,
        clearance_radius=CLEARANCE_RADIUS,
    )
    return encode_installation_profile(profile)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the generated bytes differ",
    )
    args = parser.parse_args(argv)
    generated = build_fixture()

    if args.check:
        if not args.output.is_file() or args.output.read_bytes() != generated:
            parser.error(f"fixture is stale; regenerate {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
