// Generated by tools/fixtures/generate_receiver_optics_golden.py.
// Do not edit by hand.
#pragma once

#include <cstdint>
#include "ledgrid/receiver_optics_coefficients_v1.hpp"

namespace ledgrid::golden_receiver_optics_v1 {

struct RgbVector {
  const char* id;
  std::uint16_t strength_q8_8;
  std::uint8_t input_rgb[3];
  std::int16_t unclamped_rgb[3];
  std::uint8_t expected_rgb[3];
};

constexpr RgbVector kRgbVectors[] = {
    {"black_s0", 0, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}},
    {"white_s0", 0, {255, 255, 255}, {255, 255, 255}, {255, 255, 255}},
    {"red_extreme_s0", 0, {255, 0, 0}, {255, 0, 0}, {255, 0, 0}},
    {"green_extreme_s0", 0, {0, 255, 0}, {0, 255, 0}, {0, 255, 0}},
    {"blue_extreme_s0", 0, {0, 0, 255}, {0, 0, 255}, {0, 0, 255}},
    {"warm_orange_s0", 0, {255, 128, 0}, {255, 128, 0}, {255, 128, 0}},
    {"cool_teal_s0", 0, {12, 160, 200}, {12, 160, 200}, {12, 160, 200}},
    {"muted_blue_s0", 0, {73, 99, 141}, {73, 99, 141}, {73, 99, 141}},
    {"magenta_clip_s0", 0, {255, 0, 255}, {255, 0, 255}, {255, 0, 255}},
    {"yellow_clip_s0", 0, {255, 255, 0}, {255, 255, 0}, {255, 255, 0}},
    {"black_s1", 1, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}},
    {"white_s1", 1, {255, 255, 255}, {255, 255, 255}, {255, 255, 255}},
    {"red_extreme_s1", 1, {255, 0, 0}, {255, -1, 4}, {255, 0, 4}},
    {"green_extreme_s1", 1, {0, 255, 0}, {1, 255, -3}, {1, 255, 0}},
    {"blue_extreme_s1", 1, {0, 0, 255}, {-2, 1, 255}, {0, 1, 255}},
    {"warm_orange_s1", 1, {255, 128, 0}, {256, 127, 2}, {255, 127, 2}},
    {"cool_teal_s1", 1, {12, 160, 200}, {11, 161, 198}, {11, 161, 198}},
    {"muted_blue_s1", 1, {73, 99, 141}, {73, 99, 141}, {73, 99, 141}},
    {"magenta_clip_s1", 1, {255, 0, 255}, {254, 0, 258}, {254, 0, 255}},
    {"yellow_clip_s1", 1, {255, 255, 0}, {257, 254, 0}, {255, 254, 0}},
    {"black_s64", 64, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}},
    {"white_s64", 64, {255, 255, 255}, {255, 255, 255}, {255, 255, 255}},
    {"red_extreme_s64", 64, {255, 0, 0}, {233, -37, 247}, {233, 0, 247}},
    {"green_extreme_s64", 64, {0, 255, 0}, {103, 230, -145}, {103, 230, 0}},
    {"blue_extreme_s64", 64, {0, 0, 255}, {-81, 61, 152}, {0, 61, 152}},
    {"warm_orange_s64", 64, {255, 128, 0}, {285, 79, 175}, {255, 79, 175}},
    {"cool_teal_s64", 64, {12, 160, 200}, {12, 191, 40}, {12, 191, 40}},
    {"muted_blue_s64", 64, {73, 99, 141}, {62, 113, 99}, {62, 113, 99}},
    {"magenta_clip_s64", 64, {255, 0, 255}, {152, 25, 400}, {152, 25, 255}},
    {"yellow_clip_s64", 64, {255, 255, 0}, {336, 194, 103}, {255, 194, 103}},
    {"black_s128", 128, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}},
    {"white_s128", 128, {255, 255, 255}, {255, 255, 255}, {255, 255, 255}},
    {"red_extreme_s128", 128, {255, 0, 0}, {119, -7, 395}, {119, 0, 255}},
    {"green_extreme_s128", 128, {0, 255, 0}, {234, 159, -117}, {234, 159, 0}},
    {"blue_extreme_s128", 128, {0, 0, 255}, {-98, 104, -23}, {0, 104, 0}},
    {"warm_orange_s128", 128, {255, 128, 0}, {237, 72, 336}, {237, 72, 255}},
    {"cool_teal_s128", 128, {12, 160, 200}, {75, 181, -73}, {75, 181, 0}},
    {"muted_blue_s128", 128, {73, 99, 141}, {71, 117, 55}, {71, 117, 55}},
    {"magenta_clip_s128", 128, {255, 0, 255}, {21, 96, 372}, {21, 96, 255}},
    {"yellow_clip_s128", 128, {255, 255, 0}, {353, 151, 278}, {255, 151, 255}},
    {"black_s256", 256, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}},
    {"white_s256", 256, {255, 255, 255}, {255, 255, 255}, {255, 255, 255}},
    {"red_extreme_s256", 256, {255, 0, 0}, {-102, 152, 153}, {0, 152, 153}},
    {"green_extreme_s256", 256, {0, 255, 0}, {299, 44, 300}, {255, 44, 255}},
    {"blue_extreme_s256", 256, {0, 0, 255}, {58, 58, -197}, {58, 58, 0}},
    {"warm_orange_s256", 256, {255, 128, 0}, {48, 175, 303}, {48, 175, 255}},
    {"cool_teal_s256", 256, {12, 160, 200}, {229, 81, 40}, {229, 81, 40}},
    {"muted_blue_s256", 256, {73, 99, 141}, {119, 93, 51}, {119, 93, 51}},
    {"magenta_clip_s256", 256, {255, 0, 255}, {-44, 211, -45}, {0, 211, 0}},
    {"yellow_clip_s256", 256, {255, 255, 0}, {197, 197, 452}, {197, 197, 255}},
};

struct InstalledTopologyVector {
  std::uint16_t strength_q8_8;
  const char* receiver_sha256[5];
  const char* stitched_global_sha256;
};

constexpr InstalledTopologyVector kInstalledTopologyVectors[] = {
    {64, {"ddf41cc9b8ea32ddde4bd02d35d7fe92fd1e380e6e01dfa21c3e6a148f0616da", "bbbfc97e6e39531837364055aba1b6880ae244d5e50943869cced8fc807da6c5", "f511a62f1745248e4a8f7d60307df2f09d82f6c4d7e7c138894a5154fe729497", "068fdcce994c51f1b7490cbd550164c946a27932f04171c2bb388905ca0fe74e", "f3bbd1de669599dc328ab8f25ccb2603808026abda6f5cda01af8022a3358263"}, "a914b3f48a291a86894b9830721319d39ca72c6f3a5e698d77605da46182241d"},
    {256, {"a1b204d62ce6f2df4bf45afa8f440d4d97c7883c70fd5066cc5cd2d9c29ba25b", "41993a5e3e5957eb3ed0bf4dba602f367ab6670780f33e75587468ab7b8756d8", "8cf21a10822fd2043dbe8fc9218f28c9b020f4770a55e19d1f0c4ce6a276099b", "261b62979b4515617402e9b44326719f9e1d6ffe49e401ad19b74998e0ebf5fb", "f3bbd1de669599dc328ab8f25ccb2603808026abda6f5cda01af8022a3358263"}, "0ab7059ca268b6a6982797effc65f0d95b1c3bc7f788add1c9e40ddcd49b76d4"},
};

static_assert(receiver_optics_v1::kHueStrengthMax == 256);
static_assert(receiver_optics_v1::kHueShiftMatricesQ14[0][0][0] == 16384);

}  // namespace ledgrid::golden_receiver_optics_v1
