"""Generate the receiver ABI's exact quarter-wave Q15 sine lookup table.

Uses decimal arithmetic so regeneration does not depend on the host libm.
Run with --check to verify the committed artifact without writing it.
"""

from __future__ import annotations

import argparse
from decimal import Decimal, ROUND_HALF_EVEN, localcontext
from pathlib import Path


OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "firmware/esp32/include/ledgrid/native_sin_quarter.inc"
)
PI = Decimal(
    "3.141592653589793238462643383279502884197169399375105820974944592307816406286"
)


def generate() -> str:
    values = []
    with localcontext() as context:
        context.prec = 75
        for phase in range(16385):
            angle = Decimal(phase) * PI / 32768
            term = total = angle
            for order in range(1, 60):
                term *= -angle * angle / ((2 * order) * (2 * order + 1))
                total += term
                if abs(term) < Decimal("1e-70"):
                    break
            values.append(int((total * 32767).to_integral_value(ROUND_HALF_EVEN)))
    lines = [
        "// Generated by tools/generate_native_trig_table.py; do not edit.",
        "// round_even(sin(phase * 2*pi / 65536) * 32767), phase 0..16384.",
    ]
    lines.extend(
        "    " + ", ".join(map(str, values[start : start + 16])) + ","
        for start in range(0, len(values), 16)
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit(f"Outdated sine table: {OUTPUT}")
        print("Native sine table matches generator")
    else:
        OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
