#!/usr/bin/env python3
"""Generate tiny deterministic frame and synthetic native-package fixtures."""

from __future__ import annotations

import argparse
import colorsys
from pathlib import Path

from PIL import Image

WIDTH = 32
HEIGHT = 138


def source_frames() -> list[Image.Image]:
    frames = []
    for phase in range(3):
        image = Image.new("RGB", (WIDTH, HEIGHT))
        pixels = image.load()
        for x in range(WIDTH):
            for y in range(HEIGHT):
                stripe = (x // 4 + y // 12 + phase * 2) % 6
                colors = ((255, 48, 32), (255, 190, 16), (48, 220, 72), (24, 180, 255), (96, 72, 255), (230, 48, 200))
                pixels[x, y] = colors[stripe]
        frames.append(image)
    return frames


def native_package_preview_frames() -> list[Image.Image]:
    frames = []
    for tick in range(6):
        image = Image.new("RGB", (WIDTH, HEIGHT))
        pixels = image.load()
        for x in range(WIDTH):
            for y in range(HEIGHT):
                red, green, blue = colorsys.hsv_to_rgb(((x + y) / 64.0 + tick / 6.0) % 1.0, 1.0, 1.0)
                pixels[x, y] = (round(red * 255), round(green * 255), round(blue * 255))
        frames.append(image)
    return frames


def save_sources(output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    frames = source_frames()
    frames[0].save(output / "representative.gif", save_all=True, append_images=frames[1:], duration=[80, 120, 160], loop=0, optimize=False, disposal=2)
    frames[0].save(output / "representative.webp", format="WEBP", save_all=True, append_images=frames[1:], duration=[90, 130, 170], loop=0, lossless=True, method=6, exact=True)
    # This is a package-validation fixture, not an example renderer. Production
    # native previews are generated by executing the trusted host build through
    # render_host_preview(), so preview logic cannot diverge from module logic.
    preview = native_package_preview_frames()
    preview[0].save(output / "representative-native-preview.webp", format="WEBP", save_all=True, append_images=preview[1:], duration=[80] * 6, loop=0, lossless=True, method=6, exact=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    save_sources(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
